name: Project CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Cache NPM Deps
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install NPM Deps
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Lint
        run: npm run lint